### ISSUE TITLE
flant_gitops k8s flow implementing

### ISSUE THREAD

**Issue by savelyev-an** [flant/negentropy#427]
### Use case. Why is this important?
It needs to be done before we can start at stage
### Proposed Solution
flant_gitops new pipeline:
1) No docker.build inside
2) Extra configuration: vaults list for applying migrations
3) After successful commit  -  generate, apply and batchv1.Job from werf-job.yaml in specified git_repo
    - passing by envs: 
        - COMMIT_HASH=zzzzz
        - VAULTS_B64_JSON=base64("'[{"name":"vault-root-1", "url":"http://127.0.0.1:8200/", "token":"hvs.KqN6TSCyx9CFbTxCVCORwASN"}]'")
    - what to do (only run migration or deploy+migration) - is in a scope of job template
    - delay between deploying and migration running is in a scope of job template
4) Before running specified script - check availability of all passed vaults and pass to script only tokens etc of active vaults
5) Track specified k8s job until it's "done". It will have 3 retries, in case if it fails - gitops should write static secret e.g. LAST_COMMIT with git hash commit and status "Failed" and send S1 alert to Madison, if everything is ok and job hasn't failed - git hash commit with "Completed" status and no alert sent.
6) Git commits should be verified against LAST_COMMIT and run sequentially, one by one, until each one achieves "Failed" or "Completed" status

Connection to k8s - entirely based on running vault at pod of the same k8s namespace 

DoD:
- show that flant_gitops run pre-templated k8s job with passed all specified variables
### Additional Information
No response
### Tasks:
- [x] change inside logic: 
- - using new config
- - got  passed vault tokens (only stub)
- - run passed script with envs 
- [x] test that first step is OK
- [x] implements new configuration paths
- [x] test that second one is OK
- [x] implements collecting real token
- [x] test DoD
