### ISSUE TITLE
RoleBindingsWatcher (MVP)

### ISSUE THREAD

**Issue by savelyev-an** [flant/negentropy#469]
Application which listen kafka-replica and
1) looks for everything to got events for each user:
Role changed: {roleName, [{tenantUUID, [projectUUID1, projectUUID2]}, ...] 
If user loss role, event looks like: {roleName, nil}

2) Event is processed by sending specified requests to specified endpoints
- [x] UserEffectiveRole model
- [x] UserEffectiveRole repo
- [x] creating replica at iam - send all db data into kafka topic
- [x] function of calculation of []UserEffectiveRole for specified roles and users
- [x] new project/archive project -> which roles should be recalculated // here the most difficult case
- [x] update group -> which users should be recalculated
- [x] new rolebinding/update rolebinding/archive rolebinding -> which usesrs and roles should be recalculated
- [x] update role/archive role -> what roles should be recalculated
- [x] mechanics for comparing new and old UserEffectiveRole to generate Event
- [x] graceful shutdown
- [x] authorised http client
- [x] add test to github actions

**Comment by savelyev-an** [comment]
what can produce events?
1) new tenant / delete tenant
new tenant - if users have tenantIsOptional roles
2) new project / delete project
new project - if users have allProjects rolebindings or projectIsOptional roles
3) delete user
4) update group / delete group
update group - if users/group was added/deleted
5) new rolebinding/update rolebinding/delete rolebinding
subjects/roles/tenants/projects

6) update role/delete role
update role - if changed included roles
